In [ ]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("data/GlobalWeatherRepository.csv")
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1693301400,29-08-2023 14:00,28.8,83.8,Sunny,...,7.9,11.1,1,1,5:24 AM,6:24 PM,5:39 PM,2:48 AM,Waxing Gibbous,93
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1693301400,29-08-2023 11:30,27.0,80.6,Partly cloudy,...,28.2,29.6,2,3,6:04 AM,7:19 PM,6:50 PM,3:25 AM,Waxing Gibbous,93
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1693301400,29-08-2023 10:30,28.0,82.4,Partly cloudy,...,6.4,7.9,1,1,6:16 AM,7:21 PM,6:46 PM,3:50 AM,Waxing Gibbous,93
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1693301400,29-08-2023 11:30,10.2,50.4,Sunny,...,0.5,0.8,1,1,7:16 AM,8:34 PM,8:08 PM,4:38 AM,Waxing Gibbous,93
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1693301400,29-08-2023 10:30,25.0,77.0,Partly cloudy,...,139.6,203.3,4,10,6:11 AM,6:06 PM,4:43 PM,4:41 AM,Waxing Gibbous,93

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3119 entries, 0 to 3118
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       3119 non-null   object
 1   location_name                 3119 non-null   object
 2   latitude                      3119 non-null   float64
 3   longitude                     3119 non-null   float64
 4   timezone                      3119 non-null   object
 5   last_updated_epoch            3119 non-null   int64
 6   last_updated                  3119 non-null   object
 7   temperature_celsius           3119 non-null   float64
 8   temperature_fahrenheit        3119 non-null   float64
 9   condition_text                3119 non-null   object
 10  wind_mph                      3119 non-null   float64
 11  wind_kph                      3119 non-null   float64
 12  wind_degree                   3119 non-null   int64
 13  wind_direction                3119 non-null   object
 14  pressure_mb                   3119 non-null   int64
 15  pressure_in                   3119 non-null   float64
 16  precip_mm                     3119 non-null   float64
 17  precip_in                     3119 non-null   float64
 18  humidity                      3119 non-null   int64
 19  cloud                         3119 non-null   int64
 20  feels_like_celsius            3119 non-null   float64
 21  feels_like_fahrenheit         3119 non-null   float64
 22  visibility_km                 3119 non-null   float64
 23  visibility_miles              3119 non-null   int64
 24  uv_index                      3119 non-null   int64
 25  gust_mph                      3119 non-null   float64
 26  gust_kph                      3119 non-null   float64
 27  air_quality_Carbon_Monoxide   3119 non-null   float64
 28  air_quality_Ozone             3119 non-null   float64
 29  air_quality_Nitrogen_dioxide  3119 non-null   float64
 30  air_quality_Sulphur_dioxide   3119 non-null   float64
 31  air_quality_PM2.5             3119 non-null   float64
 32  air_quality_PM10              3119 non-null   float64
 33  air_quality_us-epa-index      3119 non-null   int64
 34  air_quality_gb-defra-index    3119 non-null   int64
 35  sunrise                       3119 non-null   object
 36  sunset                        3119 non-null   object
 37  moonrise                      3119 non-null   object
 38  moonset                       3119 non-null   object
 39  moon_phase                    3119 non-null   object
 40  moon_illumination             3119 non-null   int64
dtypes: float64(20), int64(10), object(11)
memory usage: 999.2+ KB

In [4]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [5]:
df.fillna(df.mean(numeric_only=True), inplace=True)
for col in df.select_dtypes(include='object'):
    df[col].fillna(df[col].mode()[0], inplace=True)

df.isnull().sum()

C:\Users\fb0011tu\AppData\Local\Temp\ipykernel_10420\2614433359.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [6]:
df.drop_duplicates(inplace=True)
df.shape

(3119, 41)

In [7]:
if 'temperature_k' in df.columns:
    df['temperature_c'] = df['temperature_k'] - 273.15

In [8]:
num_cols = df.select_dtypes(include=['float64','int64']).columns
df[num_cols] = (df[num_cols] - df[num_cols].min()) / (df[num_cols].max() - df[num_cols].min())
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,0.721202,0.689521,Asia/Kabul,0.0,29-08-2023 14:00,0.655319,0.654846,Sunny,...,0.008272,0.009828,0.0,0.000000,5:24 AM,6:24 PM,5:39 PM,2:48 AM,Waxing Gibbous,0.923913
1,Albania,Tirana,0.785979,0.550251,Europe/Tirane,0.0,29-08-2023 11:30,0.617021,0.617021,Partly cloudy,...,0.030964,0.026979,0.2,0.222222,6:04 AM,7:19 PM,6:50 PM,3:25 AM,Waxing Gibbous,0.923913
2,Algeria,Algiers,0.742509,0.502934,Africa/Algiers,0.0,29-08-2023 10:30,0.638298,0.638298,Partly cloudy,...,0.006595,0.006861,0.0,0.000000,6:16 AM,7:21 PM,6:46 PM,3:50 AM,Waxing Gibbous,0.923913
3,Andorra,Andorra La Vella,0.797108,0.498617,Europe/Andorra,0.0,29-08-2023 11:30,0.259574,0.260047,Sunny,...,0.000000,0.000278,0.0,0.000000,7:16 AM,8:34 PM,8:08 PM,4:38 AM,Waxing Gibbous,0.923913
4,Angola,Luanda,0.308761,0.531657,Africa/Luanda,0.0,29-08-2023 10:30,0.574468,0.574468,Partly cloudy,...,0.155488,0.188022,0.6,1.000000,6:11 AM,6:06 PM,4:43 PM,4:41 AM,Waxing Gibbous,0.923913

In [9]:
num_cols = df.select_dtypes(include=['float64','int64']).columns
df[num_cols] = (df[num_cols] - df[num_cols].min()) / (df[num_cols].max() - df[num_cols].min())
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,0.721202,0.689521,Asia/Kabul,0.0,29-08-2023 14:00,0.655319,0.654846,Sunny,...,0.008272,0.009828,0.0,0.000000,5:24 AM,6:24 PM,5:39 PM,2:48 AM,Waxing Gibbous,0.923913
1,Albania,Tirana,0.785979,0.550251,Europe/Tirane,0.0,29-08-2023 11:30,0.617021,0.617021,Partly cloudy,...,0.030964,0.026979,0.2,0.222222,6:04 AM,7:19 PM,6:50 PM,3:25 AM,Waxing Gibbous,0.923913
2,Algeria,Algiers,0.742509,0.502934,Africa/Algiers,0.0,29-08-2023 10:30,0.638298,0.638298,Partly cloudy,...,0.006595,0.006861,0.0,0.000000,6:16 AM,7:21 PM,6:46 PM,3:50 AM,Waxing Gibbous,0.923913
3,Andorra,Andorra La Vella,0.797108,0.498617,Europe/Andorra,0.0,29-08-2023 11:30,0.259574,0.260047,Sunny,...,0.000000,0.000278,0.0,0.000000,7:16 AM,8:34 PM,8:08 PM,4:38 AM,Waxing Gibbous,0.923913
4,Angola,Luanda,0.308761,0.531657,Africa/Luanda,0.0,29-08-2023 10:30,0.574468,0.574468,Partly cloudy,...,0.155488,0.188022,0.6,1.000000,6:11 AM,6:06 PM,4:43 PM,4:41 AM,Waxing Gibbous,0.923913

In [10]:
df.to_csv("data/cleaned_weather_data.csv", index=False)